apiVersion: 1

datasources:
- name: 'dmarc-ag'
  type: 'elasticsearch'
  access: 'proxy'
  database: '[dmarc_aggregate-]YYYY-MM-DD'
  url: 'http://elasticsearch:9200'
  isDefault: true
  jsonData:
    esVersion: '8.x'
    timeField: 'date_range'
  version: 1
  editable: true
- name: 'dmarc-fo'
  type: 'elasticsearch'
  access: 'proxy'
  orgId: 1
  url: 'http://elasticsearch:9200'
  database: '[dmarc_forensic-]YYYY-MM-DD'
  isDefault: false
  jsonData:
    esVersion: '8.x'
    timeField: 'arrival_date'
  version: 1
  editable: true
